version: "3"
services:
  mysql :
    image: mysql:5.6
    container_name : mysql
    ports :
      - "3306:3306"
    volumes :
      #- ../src/mysql/my.cnf:/etc/mysql/mysql.conf.d/my.cnf
      - ../data/mysql/data:/var/lib/mysql
    environment :
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0 --explicit_defaults_for_timestamp
    networks:
      - mysqlNet
networks:
  mysqlNet: